--- 
title: "Sampling" 
author: "Philippe Glaziou" 
date: "`r Sys.Date()`" 
output:  
  html_fragment: 
  # Don’t include a table of contents 
  toc: no 
# Set standard figure width to 12 inches 
fig_width: 12 
# Don’t write figure captions 
fig_caption: FALSE 
--- 

# Description de l'échantillon
  
```{r setup, include=FALSE} 
# Chapter 1
# Set options, load data, utility functions 
knitr::opts_chunk$set(
  echo = FALSE,
  results = "asis",
  message = FALSE,
  warning = FALSE
)
library(data.table)
library(here)

load(here('data/steps.Rdata'))
load(here('data/report.Rdata'))

``` 

Au total, `r dim(steps)[1]` foyers ont été échantillonnés, une personne par foyer étant éligible pour participer à l'enquête. Parmi ces personnes,`r a0$N[1]` n'ont pu être investiguées (`r round(a0$percent[1], 1)`%). Le tableau 1 montre la distribution des personnes manquantes par commune.

### Tableau 1. Distribution des personnes non investiguées par commune


```{r tab_1}
a2 <- setnames(a2, names(a2), c('commune','manquant','pourcentage'))
flextable(a2)

```






