--- 
title: "Enquête STEP 2019, Polynésie Française"
subtitle: "Step 1, Questionnaire"
output:  
  html_document: 
    mode: selfcontained
    toc: yes 
    toc_float: true
    number_sections: false
    theme: flatly
fig_width: 12 
fig_caption: FALSE 
lang: fr
--- 

```{r setup, include=FALSE} 
# Chapter 1
# Set options, load data, utility functions 
knitr::opts_chunk$set(
  echo = FALSE,
  results = "asis",
  message = FALSE,
  warning = FALSE
)
library(data.table)
library(here)
library(knitr)
library(kableExtra)
library(gtsummary)
library(flextable)
library(survey)

load(here('data/report.Rdata'))

theme_gtsummary_language('fr')
theme_gtsummary_journal('lancet')

``` 

## 1.1 Tabac 

### Tableau 1.1.1a Fumeurs de produits à base de tabac 
```{r tab_1_1_1a}
d <- survey::svydesign(
  id = ~ uid,
  weights = ~ w1,
  strata = ~ gstratum + agegr,
  data = steps[enroll == 1 &
                 !is.na(tobacco.T1), .(uid,
                                    w1,
                                    gstratum,
                                    agegr,
                                    bmigr,
                                    sexe,
                                    t1 = yesno(tobacco.T1),
                                    T1 = factor(yesno(tobacco.T1), levels=0:1, labels=c("Non","Oui")))]
)

tbl_svysummary(d,
               include = c(T1),
               label = list(T1 ~ "Fumeur"),
               statistic = list(all_categorical() ~ "{p}")) |>
  modify_header(label ~ "") |>
  add_ci(
    pattern = "{stat} ({ci})",
    statistic = list(all_categorical() ~ "{conf.low} - {conf.high}")
  )  |>
  modify_header(stat_0 = "**Pourcentage (IC 95%)**") |>
  bold_labels()

```

### Tableau 1.1.1b Fumeurs, par âge et sexe
```{r tab_1_1_1b}
tab <- svyby( ~ t1, ~ agegr + sexe, d, svymean, vartype = c("ci"))
tab[, 3:5] <- round(tab[, 3:5] * 100)
names(tab) <- c('Age', 'Sexe', 'obese', 'lo', 'hi')
tab$gros <- paste0(tab$obese, ' (', tab$lo, ' - ', tab$hi, ')')
names(tab)[6] <- "Fumeur (IC 95%)"
rownames(tab) <- NULL
tab <- tab[, c(1:2, 6)]
gt::gt(tab, groupname_col = 'Sexe') |> 
 gt::tab_style(
     locations = cells_column_labels(columns = everything()),
     style     = list(
       cell_text(weight = "bold")
     )
   )

```

### Tableau 1.1.2a Ancien fumeurs de produits à base de tabac (ayant cessé de fumer)
```{r tab_1_1_2a}
d <- survey::svydesign(
  id = ~ uid,
  weights = ~ w1,
  strata = ~ gstratum + agegr,
  data = steps[enroll == 1 &
                 !is.na(tobacco.T8), .(uid,
                                    w1,
                                    gstratum,
                                    agegr,
                                    bmigr,
                                    sexe,
                                    t8 = yesno(tobacco.T8),
                                    T8 = factor(yesno(tobacco.T8), levels=0:1, labels=c("Non","Oui")))]
)

tbl_svysummary(d,
               include = c(T8),
               label = list(T8 ~ "Ancien fumeur"),
               statistic = list(all_categorical() ~ "{p}")) |>
  modify_header(label ~ "") |>
  add_ci(
    pattern = "{stat} ({ci})",
    statistic = list(all_categorical() ~ "{conf.low} - {conf.high}")
  )  |>
  modify_header(stat_0 = "**Pourcentage (IC 95%)**") |>
  bold_labels()

```

### Tableau 1.1.2b Ancien fumeurs, par âge et sexe
```{r tab_1_1_2b}
tab <- svyby( ~ t8, ~ agegr + sexe, d, svymean, vartype = c("ci"))
tab[, 3:5] <- round(tab[, 3:5] * 100)
names(tab) <- c('Age', 'Sexe', 'obese', 'lo', 'hi')
tab$gros <- paste0(tab$obese, ' (', tab$lo, ' - ', tab$hi, ')')
names(tab)[6] <- "Ancien fumeur (IC 95%)"
rownames(tab) <- NULL
tab <- tab[, c(1:2, 6)]
gt::gt(tab, groupname_col = 'Sexe') |> 
 gt::tab_style(
     locations = cells_column_labels(columns = everything()),
     style     = list(
       cell_text(weight = "bold")
     )
   )

```



## 1.2 Alcool 



## 1.3 Nutrition

